"""empty message

Revision ID: 0a594f8a51db
Revises: 
Create Date: 2021-01-27 11:38:23.057390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0a594f8a51db'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('websiteUrl', sa.Text(), nullable=False),
    sa.Column('profilePicUrl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=True),
    sa.Column('captionRawData', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('userfollowers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('followerId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['followerId'], ['users.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('images',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('imgUrl', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('taggedusers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postId', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('viewStatus', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['postId'], ['posts.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'commentlikes', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['parentPostId'], ['id'])
    op.create_foreign_key(None, 'commenttaggedusers', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'directmessages', 'users', ['receiverId'], ['id'])
    op.create_foreign_key(None, 'directmessages', 'users', ['senderId'], ['id'])
    op.create_foreign_key(None, 'hashtagposts', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'likedposts', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'likedposts', 'users', ['userId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'likedposts', type_='foreignkey')
    op.drop_constraint(None, 'likedposts', type_='foreignkey')
    op.drop_constraint(None, 'hashtagposts', type_='foreignkey')
    op.drop_constraint(None, 'directmessages', type_='foreignkey')
    op.drop_constraint(None, 'directmessages', type_='foreignkey')
    op.drop_constraint(None, 'commenttaggedusers', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'commentlikes', type_='foreignkey')
    op.drop_table('taggedusers')
    op.drop_table('images')
    op.drop_table('userfollowers')
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
