"""empty message

Revision ID: 808362841902
Revises: 6eb341cfe568
Create Date: 2021-01-26 14:21:56.777521

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '808362841902'
down_revision = '6eb341cfe568'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('state', sa.Text(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=40), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('websiteUrl', sa.Text(), nullable=False),
    sa.Column('profilePicUrl', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('userId', sa.Integer(), nullable=False),
    sa.Column('locationId', sa.Integer(), nullable=False),
    sa.Column('captionRawData', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['locationId'], ['locations.id'], ),
    sa.ForeignKeyConstraint(['userId'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'commentlikes', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'comments', 'posts', ['parentPostId'], ['id'])
    op.create_foreign_key(None, 'commenttaggedusers', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'directmessages', 'users', ['receiverId'], ['id'])
    op.create_foreign_key(None, 'directmessages', 'users', ['senderId'], ['id'])
    op.create_foreign_key(None, 'hashtagposts', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'images', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'likedposts', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'likedposts', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'taggedusers', 'posts', ['postId'], ['id'])
    op.create_foreign_key(None, 'taggedusers', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'userfollowers', 'users', ['userId'], ['id'])
    op.create_foreign_key(None, 'userfollowers', 'users', ['followerId'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'userfollowers', type_='foreignkey')
    op.drop_constraint(None, 'userfollowers', type_='foreignkey')
    op.drop_constraint(None, 'taggedusers', type_='foreignkey')
    op.drop_constraint(None, 'taggedusers', type_='foreignkey')
    op.drop_constraint(None, 'likedposts', type_='foreignkey')
    op.drop_constraint(None, 'likedposts', type_='foreignkey')
    op.drop_constraint(None, 'images', type_='foreignkey')
    op.drop_constraint(None, 'hashtagposts', type_='foreignkey')
    op.drop_constraint(None, 'directmessages', type_='foreignkey')
    op.drop_constraint(None, 'directmessages', type_='foreignkey')
    op.drop_constraint(None, 'commenttaggedusers', type_='foreignkey')
    op.drop_constraint(None, 'comments', type_='foreignkey')
    op.drop_constraint(None, 'commentlikes', type_='foreignkey')
    op.drop_table('posts')
    op.drop_table('users')
    op.drop_table('locations')
    # ### end Alembic commands ###
